### PR TITLE
samples: add Java samples

### PR DESCRIPTION
**Pull request by anweshan**

### CODE REVIEW

**Comment by averikitsch** [comment]
Thank you for the PR, but it is very large. Can you please split it into different PRs? Take a look at go/cdpe-snippet-rubric and https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md to add thorough comments to the samples. Please use `exec:exec` not `exec:java` see https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1523

**Comment by anweshan** [comment]
@averikitsch how many samples would you like per PR? I can split up the work done in this one

**Comment by averikitsch** [comment]
> @averikitsch how many samples would you like per PR? I can split up the work done in this one

Thank you, can you separate max 3 samples per PR?

**Comment by anweshan** [comment]
Closing PR as content is duplicated in smaller PRs

**Pull request closed without merging**
